apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mirroringAgentRun
spec:
  schedule: “*/1 * * * *”
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mirroringAgent
            image: sigstoremonitor/mirroring_agent
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure