#
# Copyright 2022 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Consistency proof

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0
      - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2.2.0
        with:
          go-version: 1.16
      - name: Download artifact
        uses: dawidd6/action-download-artifact@ea71f332a90fd52416b1629b933dcf7e0ccd421d # v2.22.0
        with:
          workflow: check.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: checkpoint
        # Skip on first run since there will be no checkpoint
        continue-on-error: true
      - name: Log current checkpoints
        run: cat logInfo.txt
        # Skip on first run
        continue-on-error: true
      - run: go run ./cmd/mirroring --once
      - name: Upload checkpoint
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: checkpoint
          path: logInfo.txt
          retention-days: 1
      - name: Log new checkpoints
        run: cat logInfo.txt
