
name: test rekor monitor
on:
    push:
        branches:
            - main

permissions: read-all

jobs:
    run-consistency-pro:
        permissions:
            contents: read # Needed to checkout repositories
            issues: write # Needed if you set "file_issue: true"
            id-token: write # Needed to detect the current reusable repository and ref
        uses: ee00001/rekor_monitor_test/.github/workflows/reusable_monitoring.yml@main
        with:
            file_issue: true # Strongly recommended: Files an issue on monitoring failure
            artifact_retention_days: 14 # Optional, default is 14: Must be longer than the cron job frequency
            identities: |
                certIdentities:
                    - certSubject: sigstore-prod-prometheus-sa@project-rekor\.iam.gserviceaccount\.com
                fingerprints:
                    - CDEDDE1155BDFCF5D5FE00A0BDD5966A3082B95FFC88CDD97FF0602E94A2BF4C
